name: vuln_app

services:
  backend:
    build:
      context: '.'
      dockerfile: './backend/Dockerfile'
    depends_on:
      - db
    env_file:
      - ./backend/.env
    restart: 'on-failure'
  db:
    env_file:
      - ./backend/.env
    expose:
     - '5432'
    image: 'postgres:16-alpine'
    restart: 'on-failure'
  nginx-frontend:
    build:
      context: '.'
      dockerfile: './nginx-frontend/Dockerfile'
    depends_on:
      - backend
      - db
      - pgadmin
    ports:
      - "80:80"
    restart: 'on-failure'
  pgadmin:
    depends_on:
      - db
    env_file:
      - ./pgadmin/.env
    image: dpage/pgadmin4
    networks:
      default:
        ipv4_address: 172.172.0.52
    restart: 'on-failure'

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.172.0.0/16
          ip_range: 172.172.0.0/16
          gateway: 172.172.0.1